---

# https://www.howtoforge.com/tutorial/how-to-setup-haproxy-as-load-balancer-for-nginx-on-centos-7/

- name: install haproxy
  yum: name=haproxy

- debug: msg="{{item}}"
  with_items: {{ hostvars[groups['web']] }}

- name: haproxy config
  template: src=haproxy_config.j2 dest=/etc/haproxy/haproxy.cfg
  with_dict: "{{nginx_config}}"
